module.exports = {
  apps: [
    {
      name: 'kavach-workers',
      script: './workers/index.ts',
      interpreter: 'node',
      interpreter_args: '--require ts-node/register',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      env: { NODE_ENV: 'production' },
      error_file: '/var/log/kavach/worker-error.log',
      out_file: '/var/log/kavach/worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '512M',
      restart_delay: 5000,
    },
    {
      name: 'kavach-socket',
      script: './lib/socket/server.ts',
      interpreter: 'node',
      interpreter_args: '--require ts-node/register',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      env: { NODE_ENV: 'production', PORT: '3001' },
      error_file: '/var/log/kavach/socket-error.log',
      out_file: '/var/log/kavach/socket-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '256M',
      restart_delay: 3000,
    },
  ],
}
